# Generated by Django 3.1.4 on 2020-12-12 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='blog_post',
            new_name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='post_refs',
            field=models.TextField(null=True),
        ),
    ]
